from sqlalchemy import (
    Column,
    Integer,
    Text,
    Date,
    Numeric,
    Float,
    DateTime,
    func,
)
from geoalchemy2 import Geometry
from app.db.session import Base


class Property(Base):
    __tablename__ = "properties"

    id = Column(Integer, primary_key=True, index=True)
    synthetic_stateid = Column(Text, unique=True, index=True)
    STATEID = Column(Text)
    PARCELID = Column(Text)
    TAXPARCELID = Column(Text)
    PARCELDATE = Column(Date)
    TAXROLLYEAR = Column(Numeric)
    OWNERNME1 = Column(Text)
    OWNERNME2 = Column(Text)
    PSTLADRESS = Column(Text)
    SITEADRESS = Column(Text)
    ADDNUMPREFIX = Column(Text)
    ADDNUM = Column(Text)
    ADDNUMSUFFIX = Column(Text)
    PREFIX = Column(Text)
    STREETNAME = Column(Text)
    STREETTYPE = Column(Text)
    SUFFIX = Column(Text)
    LANDMARKNAME = Column(Text)
    UNITTYPE = Column(Text)
    UNITID = Column(Text)
    PLACENAME = Column(Text)
    ZIPCODE = Column(Text)
    ZIP4 = Column(Text)
    STATE = Column(Text)
    SCHOOLDIST = Column(Text)
    SCHOOLDISTNO = Column(Text)
    CNTASSDVALUE = Column(Numeric)
    LNDVALUE = Column(Numeric)
    IMPVALUE = Column(Numeric)
    MFLVALUE = Column(Numeric)
    ESTFMKVALUE = Column(Numeric)
    NETPRPTA = Column(Numeric)
    GRSPRPTA = Column(Numeric)
    PROPCLASS = Column(Text)
    AUXCLASS = Column(Text)
    ASSDACRES = Column(Float)
    DEEDACRES = Column(Float)
    GISACRES = Column(Float)
    CONAME = Column(Text)
    LOADDATE = Column(Date)
    PARCELFIPS = Column(Text)
    PARCELSRC = Column(Text)
    LONGITUDE = Column(Float)
    LATITUDE = Column(Float)
    Shape_Length = Column(Float)
    Shape_Area = Column(Float)
    geom = Column(Geometry(geometry_type="GEOMETRY", srid=4326))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())


class PropertyEvent(Base):
    __tablename__ = "property_events"

    event_id = Column(Integer, primary_key=True, index=True)
    raw_parcel_identification = Column(Text)
    event_type = Column(Text, nullable=False)
    event_date = Column(DateTime(timezone=True), nullable=False, primary_key=True)
    source = Column(Text)
    SaleNumber = Column(Text)
    YearCaptured = Column(Integer)
    GrantorType = Column(Text)
    GrantorGranteeRelationship = Column(Text)
    WeatherStds = Column(Text)
    EnergyExclusion = Column(Text)
    Section = Column(Text)
    Township = Column(Text)
    Range = Column(Text)
    PropertyType = Column(Text)
    PredominateUse = Column(Text)
    MultiFamilyUnits = Column(Integer)
    AgrOwnerLessThan5years = Column(Text)
    TotalAcres = Column(Float)
    WaterFrontIndicator = Column(Text)
    TransferType = Column(Text)
    OwnerInterestTransferred = Column(Text)
    GrantorRightsRetained = Column(Text)
    PersPropertyValueExcluded = Column(Numeric)
    PersPropertyValueExempt = Column(Numeric)
    TotalRealEstateValue = Column(Numeric)
    TransferFee = Column(Numeric)
    TransferExemptionNumber = Column(Text)
    FinancingCode = Column(Text)
    DocumentNumber = Column(Text)
    DateRecorded = Column(Date)
    DateConveyed = Column(Date)
    DeedDate = Column(Date)
    ConveyanceCode = Column(Text)
    ParcelIdentification = Column(Text)
    MultiGrantors = Column(Text)
    GrantorLastName = Column(Text)
    GrantorFirstName = Column(Text)
    GrantorStreetNumber = Column(Text)
    GrantorAddress = Column(Text)
    GrantorCity = Column(Text)
    GrantorState = Column(Text)
    GrantorZip = Column(Text)
    CertificationDate = Column(Date)
    MultiGrantees = Column(Text)
    GranteeLastName = Column(Text)
    GranteeFirstName = Column(Text)
    GranteeStreetNumber = Column(Text)
    GranteeAddress = Column(Text)
    GranteeCity = Column(Text)
    GranteeState = Column(Text)
    GranteeZip = Column(Text)
    GranteeCertificationDate = Column(Date)
    GranteePrimaryResidence = Column(Text)
    TaxBillGrantee = Column(Text)
    CityYN = Column(Text)
    VillageYN = Column(Text)
    TownYN = Column(Text)
    TVCname = Column(Text)
    CountyName = Column(Text)
    PropertyAddress = Column(Text)
    LotSize1 = Column(Float)
    LotSize = Column(Float)
    ManagedForestLandAcres = Column(Float)
    VolumeJacket = Column(Text)
    PageImage = Column(Text)
    SplitParcel = Column(Text)
    AgentFor = Column(Text)
    AgentName = Column(Text)
    AgentStreet = Column(Text)
    AgentAddress = Column(Text)
    AgentCity = Column(Text)
    AgentState = Column(Text)
    AgentZip = Column(Text)
    PreparerName = Column(Text)
    GrantorTypeOtherNote = Column(Text)
    GrantorGranteeRelationOther = Column(Text)
    TaxBillName = Column(Text)
    TaxBillStreetNumber = Column(Text)
    TaxBillAddress = Column(Text)
    TaxBillCity = Column(Text)
    TaxBillState = Column(Text)
    TaxBillZip = Column(Text)
    W12documentNumber = Column(Text)
    PropertyTypeOtherNote = Column(Text)
    MiscUseNote = Column(Text)
    TransferTypeOtherNote = Column(Text)
    OwnerInterestOtherNote = Column(Text)
    GrantorRightsOtherNotes = Column(Text)
    PreviousDocumentNumber = Column(Text)
    ConveyanceCodeOtherNote = Column(Text)
    MiscCountyTVC = Column(Text)
    MultiTVSs = Column(Text)
    WaterFrontFeet = Column(Float)
