apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: propfinder
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 50Gi
